"""Tests for the shared export_report skill (src/agent/report_export.py)."""

from __future__ import annotations

import os

import pytest

from src.agent.report_export import _sanitise_filename, make_export_report_skill


class _FakeDB:
    def __init__(self, data_dir: str):
        self.data_dir = data_dir


def _call_export_skill(skill, **kwargs) -> str:
    """beta_tool-wrapped functions remain callable when invoked directly."""
    return skill(**kwargs)


@pytest.fixture
def export_skill(tmp_path):
    db = _FakeDB(str(tmp_path))
    return make_export_report_skill(db, agent_kind="cio"), tmp_path


def test_sanitise_strips_path_traversal() -> None:
    assert _sanitise_filename("../../etc/passwd") == "passwd.md"
    assert _sanitise_filename("/tmp/foo.md") == "foo.md"
    assert _sanitise_filename("..") is None
    assert _sanitise_filename(".") is None
    assert _sanitise_filename("") is None


def test_sanitise_replaces_unsafe_chars() -> None:
    assert _sanitise_filename("my report!.md") == "my_report_.md"
    assert _sanitise_filename("hello world") == "hello_world.md"


def test_sanitise_appends_md_when_missing() -> None:
    assert _sanitise_filename("decision_memo") == "decision_memo.md"
    assert _sanitise_filename("already.md") == "already.md"


def test_export_writes_file(export_skill) -> None:
    skill, tmp = export_skill
    result = _call_export_skill(
        skill,
        filename="wealth_review_q2",
        markdown_content="# Wealth Review\n\nLooks good.",
    )
    path = tmp / "reports" / "wealth_review_q2.md"
    assert path.exists()
    body = path.read_text()
    assert "# Wealth Review" in body
    assert "generated by cio agent at" in body
    assert "Wrote" in result and str(path) in result


def test_export_refuses_overwrite_by_default(export_skill) -> None:
    skill, tmp = export_skill
    _call_export_skill(skill, filename="memo", markdown_content="first")
    second = _call_export_skill(skill, filename="memo", markdown_content="second")
    assert second.startswith("Refused")
    assert (tmp / "reports" / "memo.md").read_text().count("first") == 1


def test_export_allows_explicit_overwrite(export_skill) -> None:
    skill, tmp = export_skill
    _call_export_skill(skill, filename="memo", markdown_content="first")
    _call_export_skill(
        skill, filename="memo", markdown_content="second body", overwrite=True
    )
    body = (tmp / "reports" / "memo.md").read_text()
    assert "second body" in body
    assert "first" not in body


def test_export_rejects_empty_content(export_skill) -> None:
    skill, _ = export_skill
    result = _call_export_skill(skill, filename="empty", markdown_content="   ")
    assert result.startswith("Error")


def test_export_rejects_empty_filename(export_skill) -> None:
    skill, _ = export_skill
    result = _call_export_skill(skill, filename="", markdown_content="hello")
    assert result.startswith("Error")


def test_export_rejects_oversized_content(export_skill) -> None:
    skill, _ = export_skill
    big = "x" * 1_000_001
    result = _call_export_skill(skill, filename="big", markdown_content=big)
    assert result.startswith("Error") and "exceeds" in result


def test_export_creates_reports_directory(tmp_path) -> None:
    db = _FakeDB(str(tmp_path / "nested" / "data"))
    skill = make_export_report_skill(db, agent_kind="wealth")
    result = _call_export_skill(
        skill, filename="r", markdown_content="# Hi"
    )
    assert "Wrote" in result
    assert os.path.isdir(tmp_path / "nested" / "data" / "reports")
