"""Shared 'export to markdown' skill for the conversational agents.

The agent composes the report content in conversation and hands it verbatim
to this skill, which writes it to ``<db.data_dir>/reports/<filename>.md``.
The skill is intentionally I/O-only — all formatting decisions belong to the
agent.

Used by ``PortfolioManagerAgent``, ``WealthAgent``, and ``CIOAgent``.
"""

from __future__ import annotations

import os
import re
from datetime import datetime, timezone

from anthropic import beta_tool

from src.database import Database

# Cap to protect against runaway agent output. 1 MB is more than enough
# for any sensible portfolio report.
_MAX_REPORT_BYTES = 1_000_000

_SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9._-]+")


def _sanitise_filename(raw: str) -> str | None:
    """Return a safe basename ending in .md, or None if the input is unusable."""
    name = (raw or "").strip()
    if not name:
        return None
    # Strip any path components — exports are always inside reports/.
    name = os.path.basename(name)
    # Reject explicit traversal attempts after basename has been taken.
    if not name or name in (".", ".."):
        return None
    # Normalise the rest of the characters into a safe set.
    name = _SAFE_NAME_RE.sub("_", name)
    if not name.lower().endswith(".md"):
        name = f"{name}.md"
    return name


def make_export_report_skill(db: Database, agent_kind: str):
    """Build an ``export_report`` beta_tool bound to ``db.data_dir`` / ``agent_kind``.

    The ``agent_kind`` ("wealth", "pm", "cio", …) is recorded in the file
    header for traceability — useful when several agents write into the
    same reports folder.
    """

    @beta_tool
    def export_report(
        filename: str,
        markdown_content: str,
        overwrite: bool = False,
    ) -> str:
        """Write a markdown report to ``<data_dir>/reports/<filename>``.

        Compose the report's content yourself in conversation, then call
        this skill once you're ready to persist it. The skill only handles
        I/O — it does not reformat or summarise.

        Args:
            filename: Basename of the report file. Path components are
                stripped; non-alphanumerics other than ``._-`` are replaced
                with ``_``. A ``.md`` extension is appended if missing.
            markdown_content: The full report body in markdown.
            overwrite: If False (default) and the file already exists,
                refuse the write and report the conflict. Set True to
                replace the existing file.
        """
        safe = _sanitise_filename(filename)
        if safe is None:
            return "Error: filename is empty or invalid."

        if not isinstance(markdown_content, str) or not markdown_content.strip():
            return "Error: markdown_content is empty."
        if len(markdown_content.encode("utf-8")) > _MAX_REPORT_BYTES:
            return (
                f"Error: markdown_content exceeds {_MAX_REPORT_BYTES:,} bytes — "
                "split the report or trim sections."
            )

        reports_dir = os.path.join(db.data_dir, "reports")
        os.makedirs(reports_dir, exist_ok=True)
        path = os.path.join(reports_dir, safe)

        if os.path.exists(path) and not overwrite:
            return (
                f"Refused: {path} already exists. Re-call with "
                "overwrite=True or pick a different filename."
            )

        header = (
            f"<!-- generated by {agent_kind} agent at "
            f"{datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')} -->\n\n"
        )
        body = header + markdown_content.rstrip() + "\n"
        try:
            with open(path, "w", encoding="utf-8") as f:
                f.write(body)
        except OSError as exc:
            return f"Error writing {path}: {exc}"

        size = os.path.getsize(path)
        preview = markdown_content.lstrip().splitlines()[0][:120] if markdown_content.strip() else ""
        return (
            f"Wrote {size:,} bytes to {path}\n"
            f"First line: {preview}"
        )

    return export_report
